### ISSUE TITLE
第一弾 : 持ってるやつをリスト化した

### ISSUE THREAD

**Issue by ryuka0214** [ExternalExte/uec20_modded#1]
ほしいものりすと(1.12.2あり)
Applied Energistics 2
Buildcraft
CraftingEX (同レシピ異なるアイテムを作れるようになる)
EnderIO
Extra Utilities 2
Grimoire of Gaia
littleMaidMob
Mekanism
NotEnoughItems
Tinkers Construct
ThermalExpansion

ほしいものりすと(1.7.10しかない)
ArsMagica 2
AppleMilkTea2
竹
BigReactors

審議すべき
All系列 (チート感ある、いる？)
Dragonmount, LittleMaidDragon (1.7.10のみ、いる？)
GVCReversion2 (いる？)
IndustrialCraft2 (Ex or Crassic?)
InventoryTweaks (いる？)
Journeymap (Rei'sがないので代用するか？)
LogisticsPipes (いる？)
MapleTree (1.7.10のみ、いる？)
Mcheli (1.7.10のみ、いる？)
Minechem (いる？)
MineFactoryReloaded (1.7.10のみ、いる？)
More Village Biome (いる？)
Railcraft (いる？)
RealTrainMod (いる？)
ShinColle (1.7.10のみ、いる？)
SlashBlade (いる？)
TacticalFrame (いる？)
TofuCraft (1.12.2 : TofuCraftReload、いる？)
TwilightForest (いる？)

ながいな

**Comment by ExternalExte** [comment]
竹modはモミジmodと統合してsakuraって名前になった
TacticalFrameは確か1.12.2だとlittle maidと競合した気がする
